### ISSUE TITLE
Poor handling of clock skew during invite processing

### ISSUE THREAD

**Issue by aredridel** [ssbc/scuttlebot#152] opened 2015-04-04 03:45 UTC
I tried to add an invite with

```
./bin.js invite.addMe "polis.nbtsc.org,+Rhv9v9F9pNxYNtQ6RTo7tZlZiW3E1uptDobN5Jzko0=.blake2s,WN7Vz4rSvm4mBE/NE5zVfZscoZ/DEqfwpQ7OrY9bdrA="
```

The pub server logged this:
```
 Error: auth timestamp (1428118540875) is older than maxAge:300000
      at EventEmitter.api.auth (/Users/aredridel/Projects/scuttlebot/lib/api.js:75:17)
      at Object.PacketStream.request (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/index.js:83:27)
      at onRequest (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:26:12)
      at Object.p.write (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:33)
      at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
      at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
      at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
      at /Users/aredridel/Projects/scuttlebot/node_modules/pull-serializer/node_modules/pull-stream/throughs.js:97:9
      at /Users/aredridel/Projects/scuttlebot/node_modules/pull-serializer/node_modules/pull-stream/throughs.js:21:7
      at pull (/Users/aredridel/Projects/scuttlebot/node_modules/pull-serializer/node_modules/pull-split/node_modules/pull-through/index.js:35:9)
```

and the local server crashed with 

```
/Users/aredridel/Projects/scuttlebot/plugins/blobs.js:148
      var id = rpc.authorized.id
                             ^
TypeError: Cannot read property 'id' of undefined
    at EventEmitter.<anonymous> (/Users/aredridel/Projects/scuttlebot/plugins/blobs.js:148:30)
    at EventEmitter.emit (events.js:129:20)
    at /Users/aredridel/Projects/scuttlebot/index.js:120:16
    at Array.requests.(anonymous function) (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:161:9)
    at onRequest (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:20:27)
    at Object.p.write (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:33)
    at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
    at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
    at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at /Users/aredridel/Projects/scuttlebot/node_modules/pull-serializer/node_modules/pull-stream/throughs.js:97:9
/Users/aredridel/Projects/scuttlebot/bin.js:208
        if(err) throw err
```

**Comment by pfraze** [comment] 2015-04-04 05:09
Gosh, I'm sorry about the bugs you're dealing with, @aredridel. I'll look into those tomorrow.

**Comment by aredridel** [comment] 2015-04-04 05:25
No worries! This is exciting stuff, and I don't mind shaking bugs out. It's fun to play with. Hopefully these are quality reports.

**Comment by pfraze** [comment] 2015-04-04 05:33
That's plenty to go with. I'll let you know if I need more info.

Thanks!

**Comment by aredridel** [comment] 2015-04-06 02:57
With debugging from the `auth-error` branch

```
AUTH DEBUG -- ERR: undefined
AUTH DEBUG -- RES: { granted: true, type: 'peer', role: 'anonymous' }
AUTH DEBUG -- RPC: { domain: null,
  _events:
   { 'remote:authorized': [ [Function], [Function] ],
     closed: [ [Function], [Function] ] },
  _maxListeners: undefined,
  add: [Function],
  publish: [Function],
  get: [Function],
  getPublicKey: [Function],
  getLatest: [Function],
  whoami: [Function],
  auth: [Function],
  relatedMessages: [Function],
  getLocal: [Function],
  createFeedStream: [Function],
  createHistoryStream: [Function],
  createLogStream: [Function],
  messagesByType: [Function],
  messagesLinkedToMessage: [Function],
  messagesLinkedToFeed: [Function],
  messagesLinkedFromFeed: [Function],
  feedsLinkedToFeed: [Function],
  feedsLinkedFromFeed: [Function],
  followedUsers: [Function],
  gossip: { seeds: [Function], peers: [Function], connect: [Function] },
  blobs:
   { get: [Function],
     has: [Function],
     add: [Function],
     ls: [Function],
     want: [Function],
     wants: [Function] },
  invite: { create: [Function], use: [Function], addMe: [Function] },
  friends: { all: [Function], hops: [Function] },
  local: { get: [Function] },
  phoenix:
   { createEventStream: [Function],
     getIndexCounts: [Function],
     createInboxStream: [Function],
     createAdvertStream: [Function],
     getRandomAdverts: [Function],
     markRead: [Function],
     markUnread: [Function],
     toggleRead: [Function],
     isRead: [Function],
     subscribe: [Function],
     unsubscribe: [Function],
     toggleSubscribed: [Function],
     isSubscribed: [Function],
     getMyProfile: [Function],
     getProfile: [Function],
     getAllProfiles: [Function],
     getNamesById: [Function],
     getNameTrustRanks: [Function],
     getName: [Function],
     getIdsByName: [Function],
     getActionItems: [Function] },
  _emit: [Function: emit],
  emit: [Function],
  createStream: [Function],
  permissions: { [Function: perms] pre: [Function], post: [Function], test: [Function] },
  closed: false,
  close: [Function],
  incoming: false,
  outgoing: true,
  _sessid: 2,
  _remoteAddress: undefined,
  task: [Function],
  _peer:
   { id: 'z9JzzewMgSfguTJviLQ+FQJbXvXeRLqe+6N5aFnfyec=.blake2s',
     port: 2000,
     host: '10.42.42.80',
     ts: 1428288707109,
     time: { connect: 0, attempt: 1428288707419 },
     connected: true } }
info 6RKi REPL 2 start
/Users/aredridel/Projects/scuttlebot/plugins/blobs.js:148
      var id = rpc.authorized.id
                             ^
TypeError: Cannot read property 'id' of undefined
    at EventEmitter.<anonymous> (/Users/aredridel/Projects/scuttlebot/plugins/blobs.js:148:30)
    at EventEmitter.emit (events.js:129:20)
    at /Users/aredridel/Projects/scuttlebot/index.js:124:16
    at Array.requests.(anonymous function) (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:161:9)
    at onRequest (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:20:27)
    at Object.p.write (/Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/packet-stream/index.js:181:33)
    at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/pull-weird.js:52:15
    at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
    at /Users/aredridel/Projects/scuttlebot/node_modules/muxrpc/node_modules/pull-stream/throughs.js:97:9
    at /Users/aredridel/Projects/scuttlebot/node_modules/pull-serializer/node_modules/pull-stream/throughs.js:97:9
```

**Comment by aredridel** [comment] 2015-04-06 02:58
(the latest one is not a manual invite, but the normal local network discovery.)

**Comment by pfraze** [comment] 2015-04-06 03:26
@dominictarr why does sbot assume that `rpc.authorized` will be set after https://github.com/ssbc/scuttlebot/blob/ecc96c576282d8f27bae29a000f67379d600b082/index.js#L112? (The blobs plugin makes that assumption https://github.com/ssbc/scuttlebot/blob/ecc96c576282d8f27bae29a000f67379d600b082/plugins/blobs.js#L148 by hooking into the `rpc:authorized` event.) Is that a bug? It won't be set until the `remote:authorized` event is emitted.

**Comment by dominictarr** [comment] 2015-04-06 10:05
I encountered this doing a different thing the other day, and I was also quite puzzeled. It wasn't designed, but that emerged as the system grew, and didn't realize it was weird until I started exploring the layered plugin api thing before christchurch nodeconf.

It's actually set here: https://github.com/ssbc/scuttlebot/blob/ecc96c576282d8f27bae29a000f67379d600b082/lib/api.js#L86 when it handles the response from the auth request sent by the _other side_.
Since your auth callback doesn't happen for an entire roundtrip, but to handle the auth request from the other side only takes half a roundtrip, as long as the other side makes the auth request before they handle your auth request (i.e. they do it as soon as they create the stream) then it's _gauranteed_ to happen before you get the callback. At first I thought it must surely be a race condition, but as I looked deeper into it I realized that since muxrpc messages are ordered then it is actually NOT a race condition. (method calls are called the same order on the receiver as they are made on the client)

It IS weird though. the whole auth thing will be cleaned up and removed from the rpc layer after adding encrypted connections.

If the other end never called auth then it would never be set. Is that what is happening? It seems that invites are working on other sbot instances... which is why I think the problem here caused by auth failing. We do not have a test for invites where auth fails.

**Comment by dominictarr** [comment] 2015-04-06 10:12
Hmm, although, since the auth is failing, surely it should never emit rpc:authorized and blobs plugin shouldn't try to do anything either?

**Comment by aredridel** [comment] 2015-04-06 14:34
I was wondering about that.

**Comment by pfraze** [comment] 2015-04-06 15:06
Yeah, I think it's the auth failure.

 - `rpc:authorized` is emitted when the remote node returns success to .auth.
 - `remote:authorized` is emitted when the local node returns success to .auth.
 - `rpc.authorized` is set when the local node returns success to .auth.

If the local .auth handling fails, the `rpc.authorized` object isn't set, but that doesn't stop `rpc:authorized` from emitting and the blobs plugin from making a bad reference.

**Comment by pfraze** [comment] 2015-04-25 18:50
This will be resolved when the new auth code comes, which will refactor the sbot auth code (should resolve the bugs with auth failure) and it will remove the invite timestamp window which allowed failures due to clockskew

**Comment by dominictarr** [comment] 2015-07-30 14:17
this was fixed by moving to secret-handshake

**Closed by dominictarr** 2015-07-30 14:17 UTC
Labels: bug
