### ISSUE TITLE
Scuttlebot install error

### ISSUE THREAD

**Issue by pfraze** [ssbc/scuttlebot#241] opened 2015-09-19 00:13 UTC
When I run `npm install --save scuttlebot` I get the following error (right after sodium compiles):

```bash
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/paulfrazee/.nvm/versions/io.js/v2.3.0/bin/iojs" "/Users/paulfrazee/.nvm/versions/io.js/v2.3.0/bin/npm" "i" "--save" "scuttlebot"
npm ERR! node v2.3.0
npm ERR! npm  v2.11.1
npm ERR! path /Users/paulfrazee/ssb-blessed-dashboard/node_modules/scuttlebot/sbot.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/paulfrazee/ssb-blessed-dashboard/node_modules/scuttlebot/sbot.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/paulfrazee/ssb-blessed-dashboard/npm-debug.log
```

I know prepublish tries to `chmod +x sbot.js` but I'm not sure if that's the cause of this particular error. @dominictarr  you know what might be going on? Node 2.3.0, npm 2.11.1.

**Comment by dominictarr** [comment] 2015-09-19 03:48
this issue is duplicate of https://github.com/ssbc/scuttlebot/issues/230

**Closed by dominictarr** 2015-09-19 03:48 UTC
