### ISSUE TITLE
npm ls fails

### ISSUE THREAD

**Issue by arj03** [ssbc/scuttlebot#534] opened 2018-09-01 20:13 UTC
Trying to publish a new version but there is a pre-publish section in package.json that runs npm ls which fails with:

```
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
```

@christianbundy any idea what causes this?

**Comment by christianbundy** [comment] 2018-09-01 20:40
@arj03 

Looks to me like https://github.com/npm/npm/issues/19393, but none of the solutions from that thread have resolved the issue for me. Weird. I've gotta run now, but I'll be back later to spend some more time debugging.

**Comment by staltz** [comment] 2018-09-01 20:48
There's been some npm storms today, just saying

**Comment by christianbundy** [comment] 2018-09-01 22:57
@arj03 

Could you try running `npm config set package-lock false`? I think we could also create a file called `.npmrc`, see `%p41LfBgYpVqd3c/yTsDWf8Phvb8/rG1f9cQyqiEEPHQ=.sha256`, but I *think* that resolves the issue. My intuition is that this is either:

- a bug with `package-lock.json`
- a bug caused by *not* using `package-lock.json`

Nothing necessarily helpful, but at least the above workaround is working for me.

**Comment by arj03** [comment] 2018-09-02 18:54
@christianbundy the .npmrc worked. Thanks! Now I'm hitting https://github.com/dominictarr/epidemic-broadcast-trees/issues/20 :rage1:

**Comment by dominictarr** [comment] 2018-09-04 18:11
scuttlebot should not have a package lock file. instead https://github.com/ssbc/scuttlebot-release has a shrinkwrap file.

**Comment by dominictarr** [comment] 2018-09-04 18:12
usually an error like that is fixed by `rm -rf node_modules && npm install`

**Comment by christianbundy** [comment] 2018-09-04 19:04
@dominictarr 

That repo doesn't look like it's received any recent Scuttlebot updates, and I would *personally* love to have package-lock files in this repo (although I understand you [don't like them in modules](%ds9YHcBlck75/aTzjKx/f9dpUQrgM1mM5IiWJjjW2GI=.sha256)). I can verify that the usual `rm -rf node_modules && npm install` isn't/wasn't working without messing with `package-lock` settings. If it's helpful, I'm on Node 10.9.0 and NPM 6.4.1.

**Comment by christianbundy** [comment] 2018-09-10 20:18
Here's a screencast and my NPM config, in case they're helpful:

[![asciicast](https://asciinema.org/a/ANMwAgiMz8qt97I61cx0G4tPL.png)](https://asciinema.org/a/ANMwAgiMz8qt97I61cx0G4tPL)

```console
$ npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.4.1 node/v10.10.0 linux x64"

; environment configs
prefix = "/home/christianbundy/.node_modules"

; userconfig /home/christianbundy/.npmrc

; node bin location = /usr/bin/node
; cwd = /home/christianbundy/Source/scuttlebot
; HOME = /home/christianbundy
; "npm config ls -l" to show all defaults.
```

**Comment by dominictarr** [comment] 2018-09-10 23:58
@christianbundy that looks like a npm bug to me. it just installed correctly, it should ls correctly.

**Comment by dominictarr** [comment] 2018-09-11 00:00
I'm not getting this error on node@8 with npm@5.6.0

**Comment by dominictarr** [comment] 2018-09-11 00:06
hmm, I didn't get this error on npm@6.2.0 either.

**Comment by christianbundy** [comment] 2018-09-11 00:38
I can downgrade to Node 8 and do some more testing in the next few days. Let me know if you have any commands you'd like me to run for debugging, and I'll plan on opening an NPM bug report if we can't think of anything.

**Comment by voglster** [comment] 2018-10-25 00:47
So I ran into this issue myself, for those who come across this my workaround was as follows:

    rm -rf ./node_modules
    rm package-lock.json
    npm i --no-optional
    npm dedup

npm ls no longer reports errors at the moment.

**Closed** 2018-10-29 13:03 UTC
Labels: bug
